2021-07-27T16:30:35.907534+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (15376), thread 'MainThread' (9976):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1284, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D8E8FE4BB0>
    |        -> <function start_polling at 0x000001D8E8749310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001D8E8749D30>
    -> <aiogram.utils.executor.Executor object at 0x000001D8E8FF4C70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001D8E73B1820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001D8E72D7790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001D8E72723A0>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001D8EA058670>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001D8EA058670>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001D8EA058670>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001D8EA058670>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001D8EA00E250>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D8E8FE4BB0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001D8E85D4820>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001D8EA00E250>
                 |    |                       -> <function Handler.notify at 0x000001D8E8663940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001D8E8FE4F40>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D8E8FE4BB0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001D8EA00E700>,)
                     |           -> <function update at 0x000001D8E9FF85E0>
                     -> Handler.HandlerObj(handler=<function update at 0x000001D8E9FF85E0>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 865, in update
    message_bank += banketniy_zal.read(41023, float) + " C   Уставка t\n"
    |               |             -> <function Modbus.read at 0x000001D8E8F67700>
    |               -> <modbus.Modbus object at 0x000001D8E573D580>
    -> 'Банкетный зал:                                                                                                    \nN/A   Пу...

TypeError: unsupported operand type(s) for +: 'float' and 'str'
2021-07-27T16:35:25.771880+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-27T16:35:27.840324+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (16128), thread 'MainThread' (7792):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1284, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001E691CC8EE0>
    |        -> <function start_polling at 0x000001E691429310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001E691429D30>
    -> <aiogram.utils.executor.Executor object at 0x000001E691CB4E80>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001E690092820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001E68FFB6790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001E68FF523A0>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001E691D9F2B0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001E691D9F2B0>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001E691D9F2B0>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001E691D9F2B0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001E691D2CEE0>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001E691CC8EE0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001E6912B4790>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001E691D2CEE0>
                 |    |                       -> <function Handler.notify at 0x000001E691343940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001E691CC89A0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001E691CC8EE0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001E691D2C760>,)
                     |           -> <function update at 0x000001E691CF9670>
                     -> Handler.HandlerObj(handler=<function update at 0x000001E691CF9670>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 865, in update
    message_bank += banketniy_zal.read(41023, "float") + " C   Уставка t\n"
    |               |             -> <function Modbus.read at 0x000001E691C47820>
    |               -> <modbus.Modbus object at 0x000001E68E42D580>
    -> 'Банкетный зал:                                                                                                    \nN/A   Пу...

TypeError: unsupported operand type(s) for +: 'float' and 'str'
2021-07-27T16:36:04.534944+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-27T16:37:23.754094+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-27T16:37:28.340580+0300 INFO Пользователь: 285239597 нажал banketniy_zal и получил доступ
2021-07-27T16:37:33.583366+0300 INFO Пользователь: 285239597 нажал banketniy_zal и получил доступ
2021-07-27T16:37:43.242604+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (6548), thread 'MainThread' (11496):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1283, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020F269D4A90>
    |        -> <function start_polling at 0x0000020F26149310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x0000020F26149D30>
    -> <aiogram.utils.executor.Executor object at 0x0000020F269E3B50>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x0000020F24DB1820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x0000020F24CD6790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x0000020F24C723A0>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000020F27A89A90>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x0000020F27A89A90>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x0000020F27A89A90>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000020F27A89A90>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x0000020F27A7AF40>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020F269D4A90>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x0000020F25FD4700>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x0000020F27A7AF40>
                 |    |                       -> <function Handler.notify at 0x0000020F26063940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x0000020F269D4E20>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020F269D4A90>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {'callback_data': {'@': 'ustan', 'temp_ust': '17', 'action': 'ust_plus', 'IP': '172.16.1.30'}}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x0000020F27A7A790>,)
                     |           -> <function update at 0x0000020F27A1C700>
                     -> Handler.HandlerObj(handler=<function update at 0x0000020F27A1C700>, spec=FullArgSpec(args=['call', 'callback_data'], varargs=...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1207, in update
    await call.message.edit_reply_markup(reply_markup=kb.bank(call.from_user.id))
          |    |                                      |       |    -> <aiogram.types.fields.Field object at 0x0000020F25EFAB80>
          |    |                                      |       -> <aiogram.types.callback_query.CallbackQuery object at 0x0000020F27A7A790>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x0000020F25F010A0>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x0000020F27A7A790>

AttributeError: module 'keyboards' has no attribute 'bank'
2021-07-27T16:39:02.357024+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-27T16:39:07.144700+0300 INFO Пользователь: 285239597 нажал banketniy_zal и получил доступ
2021-07-27T16:39:17.761550+0300 INFO Пользователь: 285239597 нажал ustan:16:ust_minus:172.16.1.30 и получил доступ
2021-07-27T16:39:22.495857+0300 INFO Пользователь: 285239597 нажал banketniy_zal и получил доступ
2021-07-27T16:40:02.718815+0300 INFO Пользователь: 285239597 нажал banketniy_zal и получил доступ
2021-07-27T16:40:10.977903+0300 INFO Пользователь: 285239597 нажал ustan:17:ust_plus:172.16.1.30 и получил доступ
2021-07-27T16:40:46.445968+0300 INFO Пользователь: 285239597 нажал ustan:18:ust_plus:172.16.1.30 и получил доступ
2021-07-27T16:40:50.946220+0300 INFO Пользователь: 285239597 нажал ustan:17:ust_minus:172.16.1.30 и получил доступ
2021-07-27T16:40:55.414453+0300 INFO Пользователь: 285239597 нажал ustan:16:ust_minus:172.16.1.30 и получил доступ
2021-07-27T17:07:33.663378+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-27T17:07:35.009881+0300 INFO Пользователь: 285239597 нажал main_menu
2021-07-27T17:07:37.404509+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:08:46.192181+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (6716), thread 'MainThread' (1988):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>
    |        -> <function start_polling at 0x000001B9944E9310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001B9944E9D30>
    -> <aiogram.utils.executor.Executor object at 0x000001B994D83EB0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001B993151820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001B993075790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001B9930123A0>
    -> <Handle <TaskStepMethWrapper object at 0x000001B995E06280>()>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskStepMethWrapper object at 0x000001B995E06280>()>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskStepMethWrapper object at 0x000001B995E06280>()>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskStepMethWrapper object at 0x000001B995E06280>()>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001B995DBD940>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001B994374880>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001B995DBD940>
                 |    |                       -> <function Handler.notify at 0x000001B994403940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001B994D831C0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001B995DBD6D0>,)
                     |           -> <function update at 0x000001B994D9D430>
                     -> Handler.HandlerObj(handler=<function update at 0x000001B994D9D430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 271, in update
    Message(call)
    |       -> <aiogram.types.callback_query.CallbackQuery object at 0x000001B995DBD6D0>
    -> <class 'message.Message'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-07-27T17:08:53.464711+0300 INFO Пользователь: 1190907870 нажал vodo и получил доступ
2021-07-27T17:09:04.861075+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (6716), thread 'MainThread' (1988):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>
    |        -> <function start_polling at 0x000001B9944E9310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001B9944E9D30>
    -> <aiogram.utils.executor.Executor object at 0x000001B994D83EB0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001B993151820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001B993075790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001B9930123A0>
    -> <Handle <TaskStepMethWrapper object at 0x000001B995F13100>()>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskStepMethWrapper object at 0x000001B995F13100>()>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskStepMethWrapper object at 0x000001B995F13100>()>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskStepMethWrapper object at 0x000001B995F13100>()>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001B995DBD5E0>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001B994374880>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001B995DBD5E0>
                 |    |                       -> <function Handler.notify at 0x000001B994403940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001B994D831C0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001B994D73DF0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001B995DBD820>,)
                     |           -> <function update at 0x000001B994D9D430>
                     -> Handler.HandlerObj(handler=<function update at 0x000001B994D9D430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 271, in update
    Message(call)
    |       -> <aiogram.types.callback_query.CallbackQuery object at 0x000001B995DBD820>
    -> <class 'message.Message'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-07-27T17:10:54.404157+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:19:34.360534+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (15540), thread 'MainThread' (15888):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1285, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001BF61FF2700>
    |        -> <function start_polling at 0x000001BF61759280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001BF61759CA0>
    -> <aiogram.utils.executor.Executor object at 0x000001BF61FEAC70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001BF603C0790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001BF602E5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001BF60282310>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001BF630496A0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001BF630496A0>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001BF630496A0>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001BF630496A0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001BF6203AE20>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001BF61FF2700>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001BF615E8220>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001BF6203AE20>
                 |    |                       -> <function Handler.notify at 0x000001BF616738B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001BF61FF2E50>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001BF61FF2700>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001BF6204C2B0>,)
                     |           -> <function update at 0x000001BF6200D430>
                     -> Handler.HandlerObj(handler=<function update at 0x000001BF6200D430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 270, in update
    await call.answer()
          |    -> <function CallbackQuery.answer at 0x000001BF61512670>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x000001BF6204C2B0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\callback_query.py", line 57, in answer
    return await self.bot.answer_callback_query(callback_query_id=self.id,
                 |    |                                           |    -> <aiogram.types.fields.Field object at 0x000001BF6150B520>
                 |    |                                           -> <aiogram.types.callback_query.CallbackQuery object at 0x000001BF6204C2B0>
                 |    -> <property object at 0x000001BF6140FB30>
                 -> <aiogram.types.callback_query.CallbackQuery object at 0x000001BF6204C2B0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2222, in answer_callback_query
    return await self.request(api.Methods.ANSWER_CALLBACK_QUERY, payload)
                 |    |       |   |       |                      -> {'callback_query_id': '1225094743006508954'}
                 |    |       |   |       -> <aiogram.utils.helper.Item object at 0x000001BF615FD1C0>
                 |    |       |   -> <class 'aiogram.bot.api.Methods'>
                 |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                 |    -> <function BaseBot.request at 0x000001BF61642F70>
                 -> <aiogram.bot.bot.Bot object at 0x000001BF61FF26D0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'callback_query_id': '1225094743006508954'}
                 |   |            |    |        |    |       |             -> 'answerCallbackQuery'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x000001BF61FF26D0>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x000001BF61FF26D0>
                 |   |            |    -> <property object at 0x000001BF61637DB0>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x000001BF61FF26D0>
                 |   -> <function make_request at 0x000001BF615FB280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x000001BF61110D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/answerCallbackQuery) [400 Bad Requ...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/answerCallbackQuery) [400 Bad Requ...
           |            |       |        -> <property object at 0x000001BF60744AE0>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/answerCallbackQuery) [400 Bad Requ...
           |            -> 'answerCallbackQuery'
           -> <function check_result at 0x000001BF615E3F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: query is too old and response timeout expired or query ID is invalid'
    |          |          -> <classmethod object at 0x000001BF615F55B0>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: query is too old and response timeout expired or query id is invalid'
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.InvalidQueryID'>

aiogram.utils.exceptions.InvalidQueryID: Query is too old and response timeout expired or query id is invalid
2021-07-27T17:19:50.804665+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:19:55.589485+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:20:00.195053+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:31:46.808376+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (15652), thread 'MainThread' (11412):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1285, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000247B2E0A8B0>
    |        -> <function start_polling at 0x00000247B2569280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x00000247B2569CA0>
    -> <aiogram.utils.executor.Executor object at 0x00000247B2E14910>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x00000247B11D0790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x00000247B10F5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x00000247B1091310>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000247B2E8B1F0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x00000247B2E8B1F0>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x00000247B2E8B1F0>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000247B2E8B1F0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x00000247B2E6A340>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000247B2E0A8B0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x00000247B23F8280>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x00000247B2E6A340>
                 |    |                       -> <function Handler.notify at 0x00000247B24838B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x00000247B2E0AC10>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000247B2E0A8B0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x00000247B2E6AA60>,)
                     |           -> <function update at 0x00000247B2E2D430>
                     -> Handler.HandlerObj(handler=<function update at 0x00000247B2E2D430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 271, in update
    Msg.send_msg(call)
    |   |        -> <aiogram.types.callback_query.CallbackQuery object at 0x00000247B2E6AA60>
    |   -> <function Msg.send_msg at 0x00000247B2D988B0>
    -> <class 'message.Msg'>

TypeError: send_msg() missing 1 required positional argument: 'call'
2021-07-27T17:32:32.429844+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:32:38.648025+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:32:42.799145+0300 INFO Пользователь: 285239597 нажал main_menu
2021-07-27T17:32:44.549834+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:32:51.481053+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:33:09.696925+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T17:33:11.756917+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (14628), thread 'MainThread' (12348):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1285, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000019CEC7D9A00>
    |        -> <function start_polling at 0x0000019CEBF49280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x0000019CEBF49CA0>
    -> <aiogram.utils.executor.Executor object at 0x0000019CEC7E3A60>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x0000019CEABB1790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x0000019CEAAD5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x0000019CEAA71310>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000019CED881670>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x0000019CED881670>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x0000019CED881670>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000019CED881670>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x0000019CEC837250>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000019CEC7D9A00>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x0000019CEBDD73A0>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x0000019CEC837250>
                 |    |                       -> <function Handler.notify at 0x0000019CEBE638B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x0000019CEC7D9D60>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000019CEC7D9A00>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x0000019CED847D60>,)
                     |           -> <function update at 0x0000019CEC7FD430>
                     -> Handler.HandlerObj(handler=<function update at 0x0000019CEC7FD430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 279, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x0000019CEBCFBAC0>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x0000019CED847D60>
          |    |                                      |  -> <function pool_menu at 0x0000019CEC1BE160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x0000019CEBCFBAF0>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x0000019CED847D60>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x0000019CEBC009F0>
                 -> <aiogram.types.message.Message object at 0x0000019CED847370>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x0000019CEBDF3580>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x0000019CEBE32F70>
                   -> <aiogram.bot.bot.Bot object at 0x0000019CEC7D99D0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x0000019CEC7D99D0>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x0000019CEC7D99D0>
                 |   |            |    -> <property object at 0x0000019CEBE27DB0>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x0000019CEC7D99D0>
                 |   -> <function make_request at 0x0000019CEBDED280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x0000019CEB900D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x0000019CEAF36950>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x0000019CEBDD2F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x0000019CEBDE4730>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T17:42:19.795863+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (14996), thread 'MainThread' (11316):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001C0215F2790>
    |        -> <function start_polling at 0x000001C020D59280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001C020D59CA0>
    -> <aiogram.utils.executor.Executor object at 0x000001C0215E9C10>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001C01F9C0790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001C01F8E6700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001C01F882310>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001C021660EB0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001C021660EB0>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001C021660EB0>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001C021660EB0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001C021647F10>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001C0215F2790>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001C020BE73A0>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001C021647F10>
                 |    |                       -> <function Handler.notify at 0x000001C020C738B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001C0215F2AF0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001C0215F2790>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001C021647250>,)
                     |           -> <function update at 0x000001C02160C430>
                     -> Handler.HandlerObj(handler=<function update at 0x000001C02160C430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 280, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x000001C020B0BAC0>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x000001C021647250>
          |    |                                      |  -> <function pool_menu at 0x000001C020FCD160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x000001C020B0BAF0>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x000001C021647250>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x000001C020A109F0>
                 -> <aiogram.types.message.Message object at 0x000001C021647460>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x000001C020C00580>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x000001C020C42F70>
                   -> <aiogram.bot.bot.Bot object at 0x000001C0215F2760>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x000001C0215F2760>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x000001C0215F2760>
                 |   |            |    -> <property object at 0x000001C020C37CC0>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x000001C0215F2760>
                 |   -> <function make_request at 0x000001C020BFB280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x000001C020710D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x000001C020545860>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x000001C020BE2F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x000001C020BF4730>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T17:57:23.491393+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (7792), thread 'MainThread' (14848):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D17F3E9A90>
    |        -> <function start_polling at 0x000001D17EB59280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001D17EB59CA0>
    -> <aiogram.utils.executor.Executor object at 0x000001D17F3F3AF0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001D17D7C1790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001D17D6E5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001D17D682310>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001D17F45FF40>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001D17F45FF40>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001D17F45FF40>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001D17F45FF40>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001D17F447430>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D17F3E9A90>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001D17E9E7430>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001D17F447430>
                 |    |                       -> <function Handler.notify at 0x000001D17EA738B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001D17F3E9DF0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001D17F3E9A90>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001D17F4470A0>,)
                     |           -> <function update at 0x000001D17F40D430>
                     -> Handler.HandlerObj(handler=<function update at 0x000001D17F40D430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 280, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x000001D17E90BCA0>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x000001D17F4470A0>
          |    |                                      |  -> <function pool_menu at 0x000001D17EDCE160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x000001D17E90BCD0>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x000001D17F4470A0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x000001D17E80FB30>
                 -> <aiogram.types.message.Message object at 0x000001D17F4471F0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x000001D17EA02610>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x000001D17EA42F70>
                   -> <aiogram.bot.bot.Bot object at 0x000001D17F3E9A60>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x000001D17F3E9A60>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x000001D17F3E9A60>
                 |   |            |    -> <property object at 0x000001D17EA37EF0>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x000001D17F3E9A60>
                 |   -> <function make_request at 0x000001D17EA03280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x000001D17E510D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x000001D17E346B30>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x000001D17E9E2F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x000001D17E9F47C0>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T17:58:48.200931+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (9616), thread 'MainThread' (14780):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000216FF7A9A60>
    |        -> <function start_polling at 0x00000216FEF19280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x00000216FEF19CA0>
    -> <aiogram.utils.executor.Executor object at 0x00000216FF7B3AC0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x00000216FDB81790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x00000216FDAA5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x00000216FDA41310>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000216FF857F10>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x00000216FF857F10>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x00000216FF857F10>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000216FF857F10>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x00000216FF807400>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000216FF7A9A60>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x00000216FEDA6400>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x00000216FF807400>
                 |    |                       -> <function Handler.notify at 0x00000216FEE338B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x00000216FF7A9DC0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000216FF7A9A60>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x00000216FF807070>,)
                     |           -> <function update at 0x00000216FF7CD430>
                     -> Handler.HandlerObj(handler=<function update at 0x00000216FF7CD430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 280, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x00000216FECCBB50>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x00000216FF807070>
          |    |                                      |  -> <function pool_menu at 0x00000216FF18D160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x00000216FECCBB80>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x00000216FF807070>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x00000216FEBD29A0>
                 -> <aiogram.types.message.Message object at 0x00000216FF8071C0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x00000216FEDC35E0>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x00000216FEE02F70>
                   -> <aiogram.bot.bot.Bot object at 0x00000216FF7A9A30>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x00000216FF7A9A30>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x00000216FF7A9A30>
                 |   |            |    -> <property object at 0x00000216FEDF7B30>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x00000216FF7A9A30>
                 |   -> <function make_request at 0x00000216FEDBD280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x00000216FE8D0D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x00000216FDF06A40>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x00000216FEDA2F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x00000216FEDB3790>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T17:59:08.112600+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (15752), thread 'MainThread' (3480):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021BB48F99A0>
    |        -> <function start_polling at 0x0000021BB4069280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x0000021BB4069CA0>
    -> <aiogram.utils.executor.Executor object at 0x0000021BB4903A00>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x0000021BB2CD1790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x0000021BB2BF5700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x0000021BB2B92310>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000021BB5968E50>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x0000021BB5968E50>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x0000021BB5968E50>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x0000021BB5968E50>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x0000021BB4957B20>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021BB48F99A0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x0000021BB3EF7340>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x0000021BB4957B20>
                 |    |                       -> <function Handler.notify at 0x0000021BB3F838B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x0000021BB48F9D00>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021BB48F99A0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x0000021BB4957430>,)
                     |           -> <function update at 0x0000021BB491E430>
                     -> Handler.HandlerObj(handler=<function update at 0x0000021BB491E430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 280, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x0000021BB3E1BA60>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x0000021BB4957430>
          |    |                                      |  -> <function pool_menu at 0x0000021BB42DD160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x0000021BB3E1BA90>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x0000021BB4957430>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x0000021BB3D1FB30>
                 -> <aiogram.types.message.Message object at 0x0000021BB4957100>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x0000021BB3EFF520>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x0000021BB3F52F70>
                   -> <aiogram.bot.bot.Bot object at 0x0000021BB48F9970>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x0000021BB48F9970>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x0000021BB48F9970>
                 |   |            |    -> <property object at 0x0000021BB3F47C70>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x0000021BB48F9970>
                 |   -> <function make_request at 0x0000021BB3F0D280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x0000021BB3A20D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x0000021BB3055B30>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x0000021BB3EF2F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x0000021BB3F066D0>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T18:00:13.913940+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:00:45.768429+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:01:17.144227+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (13988), thread 'MainThread' (12680):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1286, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000233E4189AC0>
    |        -> <function start_polling at 0x00000233E38E9280>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x00000233E38E9CA0>
    -> <aiogram.utils.executor.Executor object at 0x00000233E4193B20>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x00000233E2551790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x00000233E2476700>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x00000233E2412310>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000233E51CFF70>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x00000233E51CFF70>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x00000233E51CFF70>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x00000233E51CFF70>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x00000233E51B7460>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000233E4189AC0>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x00000233E3777460>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x00000233E51B7460>
                 |    |                       -> <function Handler.notify at 0x00000233E38038B0>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x00000233E4189E20>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000233E4189AC0>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x00000233E51B70D0>,)
                     |           -> <function update at 0x00000233E41AD430>
                     -> Handler.HandlerObj(handler=<function update at 0x00000233E41AD430>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 280, in update
    await call.message.edit_reply_markup(reply_markup=kb.pool_menu(call.from_user.id))
          |    |                                      |  |         |    -> <aiogram.types.fields.Field object at 0x00000233E369BCD0>
          |    |                                      |  |         -> <aiogram.types.callback_query.CallbackQuery object at 0x00000233E51B70D0>
          |    |                                      |  -> <function pool_menu at 0x00000233E3B5F160>
          |    |                                      -> <module 'keyboards' from 'c:\\Python\\Git\\BotPiP\\keyboards.py'>
          |    -> <aiogram.types.fields.Field object at 0x00000233E369BFD0>
          -> <aiogram.types.callback_query.CallbackQuery object at 0x00000233E51B70D0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\message.py", line 2705, in edit_reply_markup
    return await self.bot.edit_message_reply_markup(
                 |    -> <property object at 0x00000233E35A09F0>
                 -> <aiogram.types.message.Message object at 0x00000233E51B7220>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 2437, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
                   |    |       |   |       |                          -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                   |    |       |   |       -> <aiogram.utils.helper.Item object at 0x00000233E3790640>
                   |    |       |   -> <class 'aiogram.bot.api.Methods'>
                   |    |       -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...
                   |    -> <function BaseBot.request at 0x00000233E37D2F70>
                   -> <aiogram.bot.bot.Bot object at 0x00000233E4189A90>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 |   |            |    |        |    |       |             |       |     -> None
                 |   |            |    |        |    |       |             |       -> {'chat_id': 285239597, 'message_id': 400, 'reply_markup': '{"inline_keyboard": [[{"text": "Под навесом", "callback_data": "po...
                 |   |            |    |        |    |       |             -> 'editMessageReplyMarkup'
                 |   |            |    |        |    |       -> <aiogram.bot.bot.Bot object at 0x00000233E4189A90>
                 |   |            |    |        |    -> TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 |   |            |    |        -> <aiogram.bot.bot.Bot object at 0x00000233E4189A90>
                 |   |            |    -> <property object at 0x00000233E37C7DB0>
                 |   |            -> <aiogram.bot.bot.Bot object at 0x00000233E4189A90>
                 |   -> <function make_request at 0x00000233E378B280>
                 -> <module 'aiogram.bot.api' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\bot\...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           |            |       |        |             |        |             |        -> <function ClientResponse.text at 0x00000233E32A0D30>
           |            |       |        |             |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        |             |        -> 400
           |            |       |        |             -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            |       |        -> <property object at 0x00000233E30D4A40>
           |            |       -> <ClientResponse(https://api.telegram.org/bot1835374263:AAHrDOBGFDVYnk35bbisaUoPI9MsqZdgd7Q/editMessageReplyMarkup) [400 Bad R...
           |            -> 'editMessageReplyMarkup'
           -> <function check_result at 0x00000233E3772F70>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    |          |          |      -> 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
    |          |          -> <classmethod object at 0x00000233E37837F0>
    |          -> <class 'aiogram.utils.exceptions.BadRequest'>
    -> <module 'aiogram.utils.exceptions' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiog...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          |   |   |       -> 'bad request: message is not modified: specified new message content and reply markup are exactly the same as a current conte...
          |   |   -> None
          |   -> <class 'aiogram.utils.exceptions.BadRequest'>
          -> <class 'aiogram.utils.exceptions.MessageNotModified'>

aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2021-07-27T18:01:36.439185+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:02:03.465440+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:02:36.527335+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:03:35.660601+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (15416), thread 'MainThread' (10408):
Traceback (most recent call last):

  File "c:\Python\Git\BotPiP\BotPiP.py", line 1285, in <module>
    executor.start_polling(dp, skip_updates=True)
    |        |             -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001F0386A4A60>
    |        -> <function start_polling at 0x000001F037E09310>
    -> <module 'aiogram.utils.executor' from 'C:\\Users\\DIx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogra...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
    |        |                           |                      |              |           -> True
    |        |                           |                      |              -> 0.1
    |        |                           |                      -> 20
    |        |                           -> True
    |        -> <function Executor.start_polling at 0x000001F037E09D30>
    -> <aiogram.utils.executor.Executor object at 0x000001F038697AF0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 312, in start_polling
    loop.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x000001F036A71820>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x000001F036996790>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x000001F0369323A0>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001F038710FD0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x000001F038710FD0>(<Future finished result=None>)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskWakeupMethWrapper object at 0x000001F038710FD0>(<Future finished result=None>)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskWakeupMethWrapper object at 0x000001F038710FD0>(<Future finished result=None>)>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.update.Update object at 0x000001F0386F6130>,)
                     |           -> <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001F0386A4A60>>
                     -> Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 |    |                       |      |      -> <aiogram.types.fields.Field object at 0x000001F037C974C0>
                 |    |                       |      -> <aiogram.types.update.Update object at 0x000001F0386F6130>
                 |    |                       -> <function Handler.notify at 0x000001F037D23940>
                 |    -> <aiogram.dispatcher.handler.Handler object at 0x000001F0386A4DC0>
                 -> <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000001F0386A4A60>

> File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     |           |        |       -> {}
                     |           |        -> (<aiogram.types.callback_query.CallbackQuery object at 0x000001F0386F65E0>,)
                     |           -> <function update at 0x000001F0386BD4C0>
                     -> Handler.HandlerObj(handler=<function update at 0x000001F0386BD4C0>, spec=FullArgSpec(args=['call'], varargs=None, varkw=None,...

  File "c:\Python\Git\BotPiP\BotPiP.py", line 272, in update
    Msg.send_msg(CallbackQuery)
    |   |        -> <class 'aiogram.types.callback_query.CallbackQuery'>
    |   -> <function Msg.send_msg at 0x000001F038627940>
    -> <class 'message.Msg'>

  File "c:\Python\Git\BotPiP\message.py", line 25, in send_msg
    call.message.edit_text(text="Обновляю")
    |    -> <aiogram.types.fields.Field object at 0x000001F037BBBAF0>
    -> <class 'aiogram.types.callback_query.CallbackQuery'>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\fields.py", line 68, in __get__
    return self.get_value(instance)
           |    |         -> None
           |    -> <function BaseField.get_value at 0x000001F037ABB670>
           -> <aiogram.types.fields.Field object at 0x000001F037BBBAF0>

  File "C:\Users\DIx\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\types\fields.py", line 45, in get_value
    return instance.values.get(self.alias, self.default)
           |                   |    |      |    -> None
           |                   |    |      -> <aiogram.types.fields.Field object at 0x000001F037BBBAF0>
           |                   |    -> 'message'
           |                   -> <aiogram.types.fields.Field object at 0x000001F037BBBAF0>
           -> None

AttributeError: 'NoneType' object has no attribute 'values'
2021-07-27T18:20:49.127223+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:32:56.040421+0300 INFO Пользователь: 285239597 нажал main_menu
2021-07-27T18:32:59.308659+0300 INFO Пользователь: 285239597 нажал pool_menu и получил доступ
2021-07-27T18:32:59.313651+0300 INFO <b>Погода</b> - Ясно                                                                                                    
<b>Температура</b> +27 C, <b>ощущается как</b> +25 C
<b>Влажность</b> 29, <b>Давление</b> 749
<b>Рассвет</b> в 04:27, <b>Закат</b> в 20:46


2021-07-28T17:32:00.685479+0300 INFO Пользователь: 285239597 нажал rekup_pri_menu и получил доступ
2021-07-28T17:32:02.180481+0300 INFO Пользователь: 285239597 нажал main_menu
2021-07-28T17:32:18.450008+0300 INFO Пользователь: 285239597 нажал re_orang и получил доступ
2021-07-28T17:32:18.453995+0300 INFO ('14311', '0000', '000000', '000000000000', '0.059', '0.000', '-273.000', '0', '0', '0', '0', '0')
2021-07-28T17:33:28.395997+0300 INFO Пользователь: 285239597 нажал perekl и получил доступ
2021-07-28T17:33:28.457833+0300 INFO Пользователь: 285239597 нажал re_orang и получил доступ
2021-07-28T17:33:28.463815+0300 INFO ('14381', '0000', '000000', '000000000000', '0.059', '0.000', '-273.000', '0', '0', '0', '0', '0')
2021-07-28T17:33:44.349334+0300 INFO Пользователь: 285239597 нажал perekl и получил доступ
2021-07-28T17:33:44.354321+0300 INFO ('14387', '0000', '000000', '000000000000', '0.019', '0.026', '-273.000', '0', '0', '0', '0', '0')
